#!/bin/sh

# generate hdf5 files from tanks associated with specified
# pypefiles -- automatically skips 0000-training files.
#
# to convert all data for a given experiment try:
#   % dbfind bert0334 | xargs tank2hdf5
#

if [ "$1" = "" ]; then
  echo "usage: $(basename $0) [-force] pypefiles..."
elif [ "$1" = "-force" ]; then
  force="-force"
  shift
else
  force=""
fi

for f in "$@"; do
  if ! echo $f | grep -q 0000 ; then
    # first make sure p2m file is fresh
    p2m "$f"
    # then extract tank
    tank2hdf5.py $force "$f"
  fi
done


